### ISSUE TITLE
update_node should return JSON

### ISSUE THREAD

**Issue by mmunz** [freifunk/openwifimap-api#4]
$ sh -x test.sh
- curl -X PUT api.openwifimap.net/update_node/myid -d {
  "type": "node",
  "hostname": "myhostname",
  "latitude": 52.520791,
  "longitude": 13.40951,
  "updateInterval": 6000
  }

returns a simple "doc updated".

It should instead return some json with status.

**Comment by sarumpaet** [comment]
One 'standard' would be 204 without any body, but since there's no spec...
