### ISSUE TITLE
Openwifimap Json schema 

### ISSUE THREAD

**Issue by zyzo** [freifunk/openwifimap-api#5]
Hi,
Is there a valid json schema for openwifimap api ? The aim is to import freifunk routers network data into loklak (a search & map service).

Related issue : https://github.com/loklak/loklak_webclient/issues/324#issuecomment-120985671

**Comment by andrenarchy** [comment]
The [docs](https://github.com/freifunk/openwifimap-api) provide a description of the data model but there's no schema for openwifimap.
