### ISSUE TITLE
Error by querying spatial bounding box

### ISSUE THREAD

**Issue by sokai** [freifunk/openwifimap-api#6]
Hi,
today I wanted to query a spatial bounding box at openwifimap.net (like it is documented in the `API.md`. But I always get a error message.

Example query URL:
`http://openwifimap.net/api/db/view_nodes_spatial?bbox=13.08,52.45,13.71,52.57`
Output:
`{"error":"not_found","reason":"missing"}`

Can someone help me, please!?
Thanks and best regards

**Comment by andrenarchy** [comment]
You can use 

 * `https://api.openwifimap.net/view_nodes_spatial?bbox=13.08,52.45,13.71,52.57` or
 * `http://api.openwifimap.net/view_nodes_spatial?bbox=13.08,52.45,13.71,52.57` if your client does not support https

btw: I can't find the URL variant you used (with `/api/db/`) in `API.md`. Should it be fixed somewhere else?

**Comment by sokai** [comment]
@andrenarchy Thanks André, your examples (indeed) are working … :)

The used URL with `/api/db/` came from my tests for node-JSON. ATM you can use
* `https://openwifimap.net/api/db/derrida.olsr` or (like you hinted me now)
* `https://api.openwifimap.net/db/derrida.olsr`

After digging that (1st one) I thougt the API is available at `/api/db/` … So everything is documented well at all – nothing to do! :)

**Comment by andrenarchy** [comment]
ha, perfect! :smile:
